name: zawadi_design
description: A Multiplatform App to demonstrate Zawadi design and its adaptability in different devices

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0  <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  designsys:
    path: ../
  device_preview: ^0.7.4
  flutter:
    sdk: flutter
  stacked: ^2.2.5
  stacked_services: ^0.8.13
  dio: ^4.0.0
  pretty_json : ^2.0.0
  google_fonts: ^2.1.0
  cached_network_image: ^3.1.0
  auto_size_text: ^3.0.0-nullsafety.0
  logger: 
  url_launcher: ^6.0.12
  flutter_dotenv: ^5.0.2
  glassmorphism: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  stacked_generator:

flutter:
  assets:
    - .env
    - assets/images/

  uses-material-design: true

